module.exports = {
  // Users - Outgoing
  USER_CONNECTED: 'USER_CONNECTED',
  USER_TYPING: 'USER_TYPING',
  USERS_LIST_UPDATED: 'USERS_LIST_UPDATED',

  // Messages - Incoming
  NEW_MESSAGE: 'NEW_MESSAGE',

  // Messages - Outgoing
  NEW_MESSAGE_RECEIVED: 'NEW_MESSAGE_RECEIVED',
  MESSAGES_LIST_UPDATED: 'MESSAGES_LIST_UPDATED',

  // Commands - Incoming
  NEW_USER_NAME: 'NEW_USER_NAME',
  REMOVE_LAST_MESSAGE: 'REMOVE_LAST_MESSAGE',
}
